# Generated by Django 5.1.1 on 2024-11-02 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_topic_room_host_message_room_topic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-updated']},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['-updated']},
        ),
    ]
