# Generated by Django 5.1.1 on 2024-11-07 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_room_created_room_participants'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-updated', '-created']},
        ),
    ]
